### ISSUE TITLE
Step 4 here isn't required

### ISSUE THREAD

**Issue by thg-adamdean** [giantswarm/gitops-template#31]
https://github.com/giantswarm/gitops-template/blob/main/docs/add_wc_structure.md#create-flux-gpg-regular-key-pair-optional-step

I don't think

**Comment by piontec** [comment]
We have big changes on the way, including doc changes, we'll review this ticket once they are merged (should be this week).

**Comment by piontec** [comment]
Step 4 there is needed to deliver the new WC's key to the MC. Our idea here is that we create a master key for MC, then we use it to encrypt WCs' keys, put them into repo and use flux to deliver to WC as well. Let me know if some more clarification is required there.

**Comment by thg-adamdean** [comment]
Hi @piontec , can you look at this again? I really don't think it's needed. See https://github.com/TheHutGroup/ice-clusters
