### ISSUE TITLE
Clarification required at the end of documentation

### ISSUE THREAD

**Issue by thg-adamdean** [giantswarm/gitops-template#32]
> After completing all the steps, you can open a PR with the changes. Once it is merged, Flux should be ready to reconcile the new workload cluster and apps.

Should probably be clarified that adding the instance of your cluster is probably a good idea, as it can be included in the initial PR.

**Comment by piontec** [comment]
uhm, sorry, but I'm not sure what you mean. Can you please explain a bit more?
