### ISSUE TITLE
Undefined Variable Referenced without Explanation

### ISSUE THREAD

**Issue by thg-adamdean** [giantswarm/gitops-template#33]
Step 5 needs further elaboration: 

https://github.com/giantswarm/gitops-template/blob/main/docs/add_wc_instance_capi.md#creating-cluster-based-on-existing-bases

You mention the base path, but then use an undefined variable in the heredoc and don't explain it.

**Comment by piontec** [comment]
:+1: we have a doc revamp on our way, we'll double check after it's merged if this problem is still there
