### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by PG2000** [giantswarm/gitops-template#4]
Hey friends,

i like the gitops-templates. Thx for that.

I have some questions:
Am i allowed to create the resources in the flux-system namespace?
How would you handle multiple orgs and clusters within a single MC?

**Comment by piontec** [comment]
As for `flux-system` and Giant Swarm MCs: please don't create resources there. If you need a "common" place to do it, you can just use the `default` namespace.
As for multiple orgs and multiple clusters: the structure is already in place.
- add more orgs like here: https://github.com/giantswarm/gitops-template/tree/main/management-clusters/MC_NAME/organizations/ORG_NAME
- add WCs within orgs like so: https://github.com/giantswarm/gitops-template/tree/main/management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters

**Comment by piontec** [comment]
I'm not sure what you mean... it is designed to work with multiple organizations per MC, like here:
https://github.com/giantswarm/gitops-template/tree/main/management-clusters/MC_NAME/organizations/ORG_NAME
Then, you can create any number of WCs inside the org structure.

**Comment by PG2000** [comment]
Ok now it makes sense. My feedback was based on the commit from before yesterday
https://github.com/giantswarm/gitops-template/blob/3eb1aa3a2057b4b5b8fb13edb4db1df4fd2045af/management-clusters/MC_NAME/MC_NAME.yaml

**Comment by MarcelMue** [comment]
Is there anything left here to do? Should we close this issue?

**Comment by piontec** [comment]
I think so. @PG2000 don't hesitate to reopen or create a new one if you still have questions or feedback.
