### ISSUE TITLE
Questions about references

### ISSUE THREAD

**Issue by PG2000** [giantswarm/gitops-template#5]
Can't find the file
https://github.com/giantswarm/gitops-template/blob/3eb1aa3a2057b4b5b8fb13edb4db1df4fd2045af/management-clusters/kustomization.yaml#L7

Is this referenced correctly ?
https://github.com/giantswarm/gitops-template/blob/3eb1aa3a2057b4b5b8fb13edb4db1df4fd2045af/management-clusters/kustomization.yaml#L8

Is this referenced correctly ?
https://github.com/giantswarm/gitops-template/blob/3eb1aa3a2057b4b5b8fb13edb4db1df4fd2045af/management-clusters/kustomization.yaml#L9

**Comment by piontec** [comment]
No, we have to fix that :) Thanks for the ticket!
